# Example configuration file for DecomNano

# Single run is done if sweep is false
# Sweep is done if sweep is true
sweep = true
resolution = 0.2
kernel = "/opt/Wolfram/Mathematica/12.3/bin/WolframKernel"

# Fixing the bulk fraction will allow fixing the bulk fraction to specific value. This would be useful whe you want to fix it to values obtained by ICP-MS instead of calculating from the cooridination numbers obtained by the NN-XANES.
# This will reduce an error due to relatively high errors due to the cooridination numbers.
fix_bulk_fraction = false

hollow_shell = true

# You can specify the output file name. If not specified, the default name is "results.csv"
output = "Pt20Au80_AgBP1_hollow_shell_TEM_correction_results.csv"

[input]
# input section is used for input of DecomNano if sweep is false
# input section is used for input_default of SweepDecomNano if sweep is true
dP = 2.77
dA = 2.88
fA = 0.8
nAA = 6.5
nPP = 9.9
nAP = 0.6
nPA = 1.1
DA = 0
DAP = 25
DP = 0
DAPh = 0

[input_config]
# Input_config section is used for defining the sweep range of each parameter.
# It is required if sweep is true.
# It will be ignored if sweep is false.
# Accepted types are number, list and dictionary.
# A dictionary will require start, end and step, and will generate a list of range(start, end, step). end is not included as in range() function in python.
nAA = 0.5
nPP = 0.7
nAP = 0.5
nPA = 0.8
DA = { start = 0, end = 25, step = 2 }
DP = { start = 0, end = 25, step = 2 }
DAPh = { start = 0, end = 13, step = 2 }
